// Copyright 2022-2024 use-ink/contracts-ui authors & contributors
// SPDX-License-Identifier: GPL-3.0-only

import { RootLayout } from 'ui/layout';
import {
    AcademicCapIcon,
    AdjustmentsIcon,
    AnnotationIcon,
    ArchiveIcon,
    ArrowCircleDownIcon,
    ArrowCircleLeftIcon,
    ArrowCircleRightIcon,
    ArrowCircleUpIcon,
    ArrowDownIcon,
    ArrowLeftIcon,
    ArrowNarrowDownIcon,
    ArrowNarrowLeftIcon,
    ArrowNarrowRightIcon,
    ArrowNarrowUpIcon,
    ArrowRightIcon,
    ArrowSmDownIcon,
    ArrowSmLeftIcon,
    ArrowSmRightIcon,
    ArrowSmUpIcon,
    ArrowUpIcon,
    ArrowsExpandIcon,
    AtSymbolIcon,
    BackspaceIcon,
    BadgeCheckIcon,
    BanIcon,
    BeakerIcon,
    BellIcon,
    BookOpenIcon,
    BookmarkAltIcon,
    BookmarkIcon,
    BriefcaseIcon,
    CakeIcon,
    CalculatorIcon,
    CalendarIcon,
    CameraIcon,
    CashIcon,
    ChartBarIcon,
    ChartPieIcon,
    ChartSquareBarIcon,
    ChatAlt2Icon,
    ChatAltIcon,
    ChatIcon,
    CheckCircleIcon,
    CheckIcon,
    ChevronDoubleDownIcon,
    ChevronDoubleLeftIcon,
    ChevronDoubleRightIcon,
    ChevronDoubleUpIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    ChipIcon,
    ClipboardCheckIcon,
    ClipboardCopyIcon,
    ClipboardListIcon,
    ClipboardIcon,
    ClockIcon,
    CloudDownloadIcon,
    CloudUploadIcon,
    CloudIcon,
    CodeIcon,
    CogIcon,
    CollectionIcon,
    ColorSwatchIcon,
    CreditCardIcon,
    CubeTransparentIcon,
    CubeIcon,
    CurrencyBangladeshiIcon,
    CurrencyDollarIcon,
    CurrencyEuroIcon,
    CurrencyPoundIcon,
    CurrencyRupeeIcon,
    CurrencyYenIcon,
    CursorClickIcon,
    DatabaseIcon,
    DesktopComputerIcon,
    DeviceMobileIcon,
    DeviceTabletIcon,
    DocumentAddIcon,
    DocumentDownloadIcon,
    DocumentDuplicateIcon,
    DocumentRemoveIcon,
    DocumentReportIcon,
    DocumentSearchIcon,
    DocumentTextIcon,
    DocumentIcon,
    DotsCircleHorizontalIcon,
    DotsHorizontalIcon,
    DotsVerticalIcon,
    DownloadIcon,
    DuplicateIcon,
    EmojiHappyIcon,
    EmojiSadIcon,
    ExclamationCircleIcon,
    ExclamationIcon,
    ExternalLinkIcon,
    EyeOffIcon,
    EyeIcon,
    FastForwardIcon,
    FilmIcon,
    FilterIcon,
    FingerPrintIcon,
    FireIcon,
    FlagIcon,
    FolderAddIcon,
    FolderDownloadIcon,
    FolderOpenIcon,
    FolderRemoveIcon,
    FolderIcon,
    GiftIcon,
    GlobeAltIcon,
    GlobeIcon,
    HandIcon,
    HashtagIcon,
    HeartIcon,
    HomeIcon,
    IdentificationIcon,
    InboxInIcon,
    InboxIcon,
    InformationCircleIcon,
    KeyIcon,
    LibraryIcon,
    LightBulbIcon,
    LightningBoltIcon,
    LinkIcon,
    LocationMarkerIcon,
    LockClosedIcon,
    LockOpenIcon,
    LoginIcon,
    LogoutIcon,
    MailOpenIcon,
    MailIcon,
    MapIcon,
    MenuAlt1Icon,
    MenuAlt2Icon,
    MenuAlt3Icon,
    MenuAlt4Icon,
    MenuIcon,
    MicrophoneIcon,
    MinusCircleIcon,
    MinusSmIcon,
    MinusIcon,
    MoonIcon,
    MusicNoteIcon,
    NewspaperIcon,
    OfficeBuildingIcon,
    PaperAirplaneIcon,
    PaperClipIcon,
    PauseIcon,
    PencilAltIcon,
    PencilIcon,
    PhoneIncomingIcon,
    PhoneMissedCallIcon,
    PhoneOutgoingIcon,
    PhoneIcon,
    PhotographIcon,
    PlayIcon,
    PlusCircleIcon,
    PlusSmIcon,
    PlusIcon,
    PresentationChartBarIcon,
    PresentationChartLineIcon,
    PrinterIcon,
    PuzzleIcon,
    QrcodeIcon,
    QuestionMarkCircleIcon,
    ReceiptRefundIcon,
    ReceiptTaxIcon,
    RefreshIcon,
    ReplyIcon,
    RewindIcon,
    RssIcon,
    SaveAsIcon,
    SaveIcon,
    ScaleIcon,
    ScissorsIcon,
    SearchCircleIcon,
    SearchIcon,
    SelectorIcon,
    ServerIcon,
    ShareIcon,
    ShieldCheckIcon,
    ShieldExclamationIcon,
    ShoppingBagIcon,
    ShoppingCartIcon,
    SortAscendingIcon,
    SortDescendingIcon,
    SparklesIcon,
    SpeakerphoneIcon,
    StarIcon,
    StatusOfflineIcon,
    StatusOnlineIcon,
    StopIcon,
    SunIcon,
    SupportIcon,
    SwitchHorizontalIcon,
    SwitchVerticalIcon,
    TableIcon,
    TagIcon,
    TemplateIcon,
    TerminalIcon,
    ThumbDownIcon,
    ThumbUpIcon,
    TicketIcon,
    TranslateIcon,
    TrashIcon,
    TrendingDownIcon,
    TrendingUpIcon,
    TruckIcon,
    UploadIcon,
    UserAddIcon,
    UserCircleIcon,
    UserGroupIcon,
    UserRemoveIcon,
    UserIcon,
    UsersIcon,
    VariableIcon,
    VideoCameraIcon,
    ViewBoardsIcon,
    ViewGridAddIcon,
    ViewGridIcon,
    ViewListIcon,
    VolumeOffIcon,
    VolumeUpIcon,
    WifiIcon,
    XCircleIcon,
    XIcon,
    ZoomInIcon,
    ZoomOutIcon,
} from '@heroicons/react/outline';
import React from 'react';


const ICONS = [
    { comp: AdjustmentsIcon, name: 'AdjustmentsIcon' },
    { comp: AcademicCapIcon, name: 'AcademicCapIcon' },
    { comp: AnnotationIcon, name: 'AnnotationIcon' },
    { comp: ArchiveIcon, name: 'ArchiveIcon' },
    { comp: ArrowCircleDownIcon, name: 'ArrowCircleDownIcon' },
    { comp: ArrowCircleLeftIcon, name: 'ArrowCircleLeftIcon' },
    { comp: ArrowCircleRightIcon, name: 'ArrowCircleRightIcon' },
    { comp: ArrowCircleUpIcon, name: 'ArrowCircleUpIcon' },
    { comp: ArrowDownIcon, name: 'ArrowDownIcon' },
    { comp: ArrowLeftIcon, name: 'ArrowLeftIcon' },
    { comp: ArrowNarrowDownIcon, name: 'ArrowNarrowDownIcon' },
    { comp: ArrowNarrowLeftIcon, name: 'ArrowNarrowLeftIcon' },
    { comp: ArrowNarrowRightIcon, name: 'ArrowNarrowRightIcon' },
    { comp: ArrowNarrowUpIcon, name: 'ArrowNarrowUpIcon' },
    { comp: ArrowRightIcon, name: 'ArrowRightIcon' },
    { comp: ArrowSmDownIcon, name: 'ArrowSmDownIcon' },
    { comp: ArrowSmLeftIcon, name: 'ArrowSmLeftIcon' },
    { comp: ArrowSmRightIcon, name: 'ArrowSmRightIcon' },
    { comp: ArrowSmUpIcon, name: 'ArrowSmUpIcon' },
    { comp: ArrowUpIcon, name: 'ArrowUpIcon' },
    { comp: ArrowsExpandIcon, name: 'ArrowsExpandIcon' },
    { comp: AtSymbolIcon, name: 'AtSymbolIcon' },
    { comp: BackspaceIcon, name: 'BackspaceIcon' },
    { comp: BadgeCheckIcon, name: 'BadgeCheckIcon' },
    { comp: BanIcon, name: 'BanIcon' },
    { comp: BeakerIcon, name: 'BeakerIcon' },
    { comp: BellIcon, name: 'BellIcon' },
    { comp: BookOpenIcon, name: 'BookOpenIcon' },
    { comp: BookmarkAltIcon, name: 'BookmarkAltIcon' },
    { comp: BookmarkIcon, name: 'BookmarkIcon' },
    { comp: BriefcaseIcon, name: 'BriefcaseIcon' },
    { comp: CakeIcon, name: 'CakeIcon' },
    { comp: CalculatorIcon, name: 'CalculatorIcon' },
    { comp: CalendarIcon, name: 'CalendarIcon' },
    { comp: CameraIcon, name: 'CameraIcon' },
    { comp: CashIcon, name: 'CashIcon' },
    { comp: ChartBarIcon, name: 'ChartBarIcon' },
    { comp: ChartPieIcon, name: 'ChartPieIcon' },
    { comp: ChartSquareBarIcon, name: 'ChartSquareBarIcon' },
    { comp: ChatAlt2Icon, name: 'ChatAlt2Icon' },
    { comp: ChatAltIcon, name: 'ChatAltIcon' },
    { comp: ChatIcon, name: 'ChatIcon' },
    { comp: CheckCircleIcon, name: 'CheckCircleIcon' },
    { comp: CheckIcon, name: 'CheckIcon' },
    { comp: ChevronDoubleDownIcon, name: 'ChevronDoubleDownIcon' },
    { comp: ChevronDoubleLeftIcon, name: 'ChevronDoubleLeftIcon' },
    { comp: ChevronDoubleRightIcon, name: 'ChevronDoubleRightIcon' },
    { comp: ChevronDoubleUpIcon, name: 'ChevronDoubleUpIcon' },
    { comp: ChevronDownIcon, name: 'ChevronDownIcon' },
    { comp: ChevronLeftIcon, name: 'ChevronLeftIcon' },
    { comp: ChevronRightIcon, name: 'ChevronRightIcon' },
    { comp: ChevronUpIcon, name: 'ChevronUpIcon' },
    { comp: ChipIcon, name: 'ChipIcon' },
    { comp: ClipboardCheckIcon, name: 'ClipboardCheckIcon' },
    { comp: ClipboardCopyIcon, name: 'ClipboardCopyIcon' },
    { comp: ClipboardListIcon, name: 'ClipboardListIcon' },
    { comp: ClipboardIcon, name: 'ClipboardIcon' },
    { comp: ClockIcon, name: 'ClockIcon' },
    { comp: CloudDownloadIcon, name: 'CloudDownloadIcon' },
    { comp: CloudUploadIcon, name: 'CloudUploadIcon' },
    { comp: CloudIcon, name: 'CloudIcon' },
    { comp: CodeIcon, name: 'CodeIcon' },
    { comp: CogIcon, name: 'CogIcon' },
    { comp: CollectionIcon, name: 'CollectionIcon' },
    { comp: ColorSwatchIcon, name: 'ColorSwatchIcon' },
    { comp: CreditCardIcon, name: 'CreditCardIcon' },
    { comp: CubeTransparentIcon, name: 'CubeTransparentIcon' },
    { comp: CubeIcon, name: 'CubeIcon' },
    { comp: CurrencyBangladeshiIcon, name: 'CurrencyBangladeshiIcon' },
    { comp: CurrencyDollarIcon, name: 'CurrencyDollarIcon' },
    { comp: CurrencyEuroIcon, name: 'CurrencyEuroIcon' },
    { comp: CurrencyPoundIcon, name: 'CurrencyPoundIcon' },
    { comp: CurrencyRupeeIcon, name: 'CurrencyRupeeIcon' },
    { comp: CurrencyYenIcon, name: 'CurrencyYenIcon' },
    { comp: CursorClickIcon, name: 'CursorClickIcon' },
    { comp: DatabaseIcon, name: 'DatabaseIcon' },
    { comp: DesktopComputerIcon, name: 'DesktopComputerIcon' },
    { comp: DeviceMobileIcon, name: 'DeviceMobileIcon' },
    { comp: DeviceTabletIcon, name: 'DeviceTabletIcon' },
    { comp: DocumentAddIcon, name: 'DocumentAddIcon' },
    { comp: DocumentDownloadIcon, name: 'DocumentDownloadIcon' },
    { comp: DocumentDuplicateIcon, name: 'DocumentDuplicateIcon' },
    { comp: DocumentRemoveIcon, name: 'DocumentRemoveIcon' },
    { comp: DocumentReportIcon, name: 'DocumentReportIcon' },
    { comp: DocumentSearchIcon, name: 'DocumentSearchIcon' },
    { comp: DocumentTextIcon, name: 'DocumentTextIcon' },
    { comp: DocumentIcon, name: 'DocumentIcon' },
    { comp: DotsCircleHorizontalIcon, name: 'DotsCircleHorizontalIcon' },
    { comp: DotsHorizontalIcon, name: 'DotsHorizontalIcon' },
    { comp: DotsVerticalIcon, name: 'DotsVerticalIcon' },
    { comp: DownloadIcon, name: 'DownloadIcon' },
    { comp: DuplicateIcon, name: 'DuplicateIcon' },
    { comp: EmojiHappyIcon, name: 'EmojiHappyIcon' },
    { comp: EmojiSadIcon, name: 'EmojiSadIcon' },
    { comp: ExclamationCircleIcon, name: 'ExclamationCircleIcon' },
    { comp: ExclamationIcon, name: 'ExclamationIcon' },
    { comp: ExternalLinkIcon, name: 'ExternalLinkIcon' },
    { comp: EyeOffIcon, name: 'EyeOffIcon' },
    { comp: EyeIcon, name: 'EyeIcon' },
    { comp: FastForwardIcon, name: 'FastForwardIcon' },
    { comp: FilmIcon, name: 'FilmIcon' },
    { comp: FilterIcon, name: 'FilterIcon' },
    { comp: FingerPrintIcon, name: 'FingerPrintIcon' },
    { comp: FireIcon, name: 'FireIcon' },
    { comp: FlagIcon, name: 'FlagIcon' },
    { comp: FolderAddIcon, name: 'FolderAddIcon' },
    { comp: FolderDownloadIcon, name: 'FolderDownloadIcon' },
    { comp: FolderOpenIcon, name: 'FolderOpenIcon' },
    { comp: FolderRemoveIcon, name: 'FolderRemoveIcon' },
    { comp: FolderIcon, name: 'FolderIcon' },
    { comp: GiftIcon, name: 'GiftIcon' },
    { comp: GlobeAltIcon, name: 'GlobeAltIcon' },
    { comp: GlobeIcon, name: 'GlobeIcon' },
    { comp: HandIcon, name: 'HandIcon' },
    { comp: HashtagIcon, name: 'HashtagIcon' },
    { comp: HeartIcon, name: 'HeartIcon' },
    { comp: HomeIcon, name: 'HomeIcon' },
    { comp: IdentificationIcon, name: 'IdentificationIcon' },
    { comp: InboxInIcon, name: 'InboxInIcon' },
    { comp: InboxIcon, name: 'InboxIcon' },
    { comp: InformationCircleIcon, name: 'InformationCircleIcon' },
    { comp: KeyIcon, name: 'KeyIcon' },
    { comp: LibraryIcon, name: 'LibraryIcon' },
    { comp: LightBulbIcon, name: 'LightBulbIcon' },
    { comp: LightningBoltIcon, name: 'LightningBoltIcon' },
    { comp: LinkIcon, name: 'LinkIcon' },
    { comp: LocationMarkerIcon, name: 'LocationMarkerIcon' },
    { comp: LockClosedIcon, name: 'LockClosedIcon' },
    { comp: LockOpenIcon, name: 'LockOpenIcon' },
    { comp: LoginIcon, name: 'LoginIcon' },
    { comp: LogoutIcon, name: 'LogoutIcon' },
    { comp: MailOpenIcon, name: 'MailOpenIcon' },
    { comp: MailIcon, name: 'MailIcon' },
    { comp: MapIcon, name: 'MapIcon' },
    { comp: MenuAlt1Icon, name: 'MenuAlt1Icon' },
    { comp: MenuAlt2Icon, name: 'MenuAlt2Icon' },
    { comp: MenuAlt3Icon, name: 'MenuAlt3Icon' },
    { comp: MenuAlt4Icon, name: 'MenuAlt4Icon' },
    { comp: MenuIcon, name: 'MenuIcon' },
    { comp: MicrophoneIcon, name: 'MicrophoneIcon' },
    { comp: MinusCircleIcon, name: 'MinusCircleIcon' },
    { comp: MinusSmIcon, name: 'MinusSmIcon' },
    { comp: MinusIcon, name: 'MinusIcon' },
    { comp: MoonIcon, name: 'MoonIcon' },
    { comp: MusicNoteIcon, name: 'MusicNoteIcon' },
    { comp: NewspaperIcon, name: 'NewspaperIcon' },
    { comp: OfficeBuildingIcon, name: 'OfficeBuildingIcon' },
    { comp: PaperAirplaneIcon, name: 'PaperAirplaneIcon' },
    { comp: PaperClipIcon, name: 'PaperClipIcon' },
    { comp: PauseIcon, name: 'PauseIcon' },
    { comp: PencilAltIcon, name: 'PencilAltIcon' },
    { comp: PencilIcon, name: 'PencilIcon' },
    { comp: PhoneIncomingIcon, name: 'PhoneIncomingIcon' },
    { comp: PhoneMissedCallIcon, name: 'PhoneMissedCallIcon' },
    { comp: PhoneOutgoingIcon, name: 'PhoneOutgoingIcon' },
    { comp: PhoneIcon, name: 'PhoneIcon' },
    { comp: PhotographIcon, name: 'PhotographIcon' },
    { comp: PlayIcon, name: 'PlayIcon' },
    { comp: PlusCircleIcon, name: 'PlusCircleIcon' },
    { comp: PlusSmIcon, name: 'PlusSmIcon' },
    { comp: PlusIcon, name: 'PlusIcon' },
    { comp: PresentationChartBarIcon, name: 'PresentationChartBarIcon' },
    { comp: PresentationChartLineIcon, name: 'PresentationChartLineIcon' },
    { comp: PrinterIcon, name: 'PrinterIcon' },
    { comp: PuzzleIcon, name: 'PuzzleIcon' },
    { comp: QrcodeIcon, name: 'QrcodeIcon' },
    { comp: QuestionMarkCircleIcon, name: 'QuestionMarkCircleIcon' },
    { comp: ReceiptRefundIcon, name: 'ReceiptRefundIcon' },
    { comp: ReceiptTaxIcon, name: 'ReceiptTaxIcon' },
    { comp: RefreshIcon, name: 'RefreshIcon' },
    { comp: ReplyIcon, name: 'ReplyIcon' },
    { comp: RewindIcon, name: 'RewindIcon' },
    { comp: RssIcon, name: 'RssIcon' },
    { comp: SaveAsIcon, name: 'SaveAsIcon' },
    { comp: SaveIcon, name: 'SaveIcon' },
    { comp: ScaleIcon, name: 'ScaleIcon' },
    { comp: ScissorsIcon, name: 'ScissorsIcon' },
    { comp: SearchCircleIcon, name: 'SearchCircleIcon' },
    { comp: SearchIcon, name: 'SearchIcon' },
    { comp: SelectorIcon, name: 'SelectorIcon' },
    { comp: ServerIcon, name: 'ServerIcon' },
    { comp: ShareIcon, name: 'ShareIcon' },
    { comp: ShieldCheckIcon, name: 'ShieldCheckIcon' },
    { comp: ShieldExclamationIcon, name: 'ShieldExclamationIcon' },
    { comp: ShoppingBagIcon, name: 'ShoppingBagIcon' },
    { comp: ShoppingCartIcon, name: 'ShoppingCartIcon' },
    { comp: SortAscendingIcon, name: 'SortAscendingIcon' },
    { comp: SortDescendingIcon, name: 'SortDescendingIcon' },
    { comp: SparklesIcon, name: 'SparklesIcon' },
    { comp: SpeakerphoneIcon, name: 'SpeakerphoneIcon' },
    { comp: StarIcon, name: 'StarIcon' },
    { comp: StatusOfflineIcon, name: 'StatusOfflineIcon' },
    { comp: StatusOnlineIcon, name: 'StatusOnlineIcon' },
    { comp: StopIcon, name: 'StopIcon' },
    { comp: SunIcon, name: 'SunIcon' },
    { comp: SupportIcon, name: 'SupportIcon' },
    { comp: SwitchHorizontalIcon, name: 'SwitchHorizontalIcon' },
    { comp: SwitchVerticalIcon, name: 'SwitchVerticalIcon' },
    { comp: TableIcon, name: 'TableIcon' },
    { comp: TagIcon, name: 'TagIcon' },
    { comp: TemplateIcon, name: 'TemplateIcon' },
    { comp: TerminalIcon, name: 'TerminalIcon' },
    { comp: ThumbDownIcon, name: 'ThumbDownIcon' },
    { comp: ThumbUpIcon, name: 'ThumbUpIcon' },
    { comp: TicketIcon, name: 'TicketIcon' },
    { comp: TranslateIcon, name: 'TranslateIcon' },
    { comp: TrashIcon, name: 'TrashIcon' },
    { comp: TrendingDownIcon, name: 'TrendingDownIcon' },
    { comp: TrendingUpIcon, name: 'TrendingUpIcon' },
    { comp: TruckIcon, name: 'TruckIcon' },
    { comp: UploadIcon, name: 'UploadIcon' },
    { comp: UserAddIcon, name: 'UserAddIcon' },
    { comp: UserCircleIcon, name: 'UserCircleIcon' },
    { comp: UserGroupIcon, name: 'UserGroupIcon' },
    { comp: UserRemoveIcon, name: 'UserRemoveIcon' },
    { comp: UserIcon, name: 'UserIcon' },
    { comp: UsersIcon, name: 'UsersIcon' },
    { comp: VariableIcon, name: 'VariableIcon' },
    { comp: VideoCameraIcon, name: 'VideoCameraIcon' },
    { comp: ViewBoardsIcon, name: 'ViewBoardsIcon' },
    { comp: ViewGridAddIcon, name: 'ViewGridAddIcon' },
    { comp: ViewGridIcon, name: 'ViewGridIcon' },
    { comp: ViewListIcon, name: 'ViewListIcon' },
    { comp: VolumeOffIcon, name: 'VolumeOffIcon' },
    { comp: VolumeUpIcon, name: 'VolumeUpIcon' },
    { comp: WifiIcon, name: 'WifiIcon' },
    { comp: XCircleIcon, name: 'XCircleIcon' },
    { comp: XIcon, name: 'XIcon' },
    { comp: ZoomInIcon, name: 'ZoomInIcon' },
    { comp: ZoomOutIcon, name: 'ZoomOutIcon' },
]
console.log(ICONS)

export function IconPage() {
    return (
        <RootLayout
            heading="IconPage"
        >
            <div className='flex flex-row gap-3 flex-wrap'>
                {ICONS.map((icon) => (
                    <div className='flex flex-col items-center' key={icon.name}>
                        {React.createElement(icon.comp, { 'aria-hidden': true, className: 'h-8 w-8 dark:text-gray-500' })}
                        <span>{icon.name}</span>
                    </div>
                ))}
                {/* <ChatAltIcon aria-hidden="true" className="mr-2 h-4 w-4 dark:text-gray-500" /> */}
            </div>
        </RootLayout>
    );
}
